[tool.poetry]
name = "infra-project"
version = "0.1.0"
description = ""
authors = ["arisromil <arisromil@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
